
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "arka"
version = "0.0.1"
dependencies = [
    'python_version >= "3.10"'
]

[tool.setuptools.packages.find]
where = ["arka"]
