version: 2.1

jobs:
  build-image:
    docker:
      - image: python:alpine
    steps:
      - run:
          name: Install dependencies
          command: "apk add --no-cache git openssh"
      - run:
          name: "Install from source"
          command: |
            git clone https://github.com/trstovall/coin.git project
            cd ./project
            python setup.py install
            cd ..
            rm -rf ./project

workflows:
  build-workflow:
    jobs:
      - build-image
