#
name: Build `arka_builder` Docker image as base image for building `arka` image

on:
  push:
    branches: [ "arka_builder" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: arka_builder
      DOCKER_USERNAME: trstovall

    steps:

    - name: Checkout Dockerfile
      uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build arka_builder base image
      run: docker build . -t $IMAGE_NAME:latest -f $IMAGE_NAME.Dockerfile

    - name: Tag arka_builder base image
      run: docker tag $IMAGE_NAME:latest $DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Push arka_builder base image
      run: docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
