name: Build, Test, and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up QEMU
        if: runner.os == 'Linux' && runner.arch == 'X64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
  
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build cibuildwheel

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          # configure cibuildwheel on Linux to build native archs ('auto'),
          # and to split the remaining architectures between the x86_64 and
          # ARM runners
          # armv7l can be built without QEMU on GitHub Actions ARM runners but that's
          # not the case on all ARM64 hardware hence 'auto armv7l' for native archs
          # on the GHA ARM64 runner
          CIBW_ARCHS_LINUX: ${{ runner.arch == 'X64' && 'auto ppc64le s390x' || 'auto armv7l' }}
  
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build-sdist:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build cibuildwheel

      - name: Build sdist
        run: python -m build --sdist --outdir dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: |
            dist/*.tar.gz

  test-wheels:
    name: Test wheels on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    env:
      TOXENV: py${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/

      - name: Install tox and wheel
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          python -m pip install tox

          PY_TAG="cp$(echo \"$PYTHON_VERSION\" | tr -d .)"

          case "${{ matrix.os }}" in
            ubuntu-latest)
              PLATFORM_TAG="manylinux_x86_64"
              ;;
            ubuntu-24.04-arm)
              PLATFORM_TAG="manylinux_aarch64"
              ;;
            windows-latest)
              PLATFORM_TAG="win_amd64"
              ;;
            macos-13)
              PLATFORM_TAG="macosx_10_9_x86_64"
              ;;
            macos-14)
              PLATFORM_TAG="macosx_11_0_arm64"
              ;;
            *)
              echo "Unsupported OS: ${{ matrix.os }}"
              exit 1
              ;;
          esac

          WHEEL=$(ls wheelhouse/*${PY_TAG}*${PLATFORM_TAG}*.whl | head -n 1)

          echo "$WHEEL"

          if [ -z "$WHEEL" ]; then
            echo "No matching wheel found for $PY_TAG + $PLATFORM_TAG"
            ls wheelhouse/
            exit 1
          fi

          python -m pip install "$WHEEL"
    
      - name: Install tox and wheel
        run: |
          python -m pip install tox
          WHEEL_FILE=$(ls wheelhouse/*.whl | head -n 1)
          python -m pip install "$WHEEL_FILE"

      - name: Run tox
        run: tox

  test-emulated:
    name: Test emulated architectures
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ppc64le, s390x, armv7l]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    container:
      image: quay.io/pypa/manylinux2014_${{ matrix.arch }}

    steps:
      - name: Install Python and deps
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          PY_TAG="cp$(echo \"$PYTHON_VERSION\" | tr -d .)"
          /opt/python/${PY_TAG}-${PY_TAG}*/bin/pip install tox

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-ubuntu-latest
          path: wheelhouse/

      - name: Install and test wheel
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          PY_TAG="cp$(echo \"$PYTHON_VERSION\" | tr -d .)"
          WHEEL=$(ls wheelhouse/*${PY_TAG}*${{ matrix.arch }}*.whl | head -n 1)
          /opt/python/${PY_TAG}-${PY_TAG}*/bin/pip install "$WHEEL"
          /opt/python/${PY_TAG}-${PY_TAG}*/bin/tox
      
  test-sdist:
    name: Test sdist on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    needs: build-sdist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    env:
      TOXENV: py${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: dist/

      - name: Install from sdist
        run: |
          python -m pip install tox
          SDIST_FILE=$(ls dist/*.tar.gz | head -n 1)
          python -m pip install "$SDIST_FILE"
        shell: bash

      - name: Run tox
        run: tox

  test-alpine:
    name: Test on Alpine (musllinux) for wheels and sdist
    needs: [build, build-sdist]
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/musllinux_1_1_x86_64

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Install Alpine dependencies
        run: |
          apk add --no-cache python3 py3-pip py3-wheel py3-setuptools py3-tox bash

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: /work

      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-wheels-*
          path: /wheels

      - name: Test wheel for musllinux on Python ${{ matrix.python-version }}
        env:
          TOXENV: py${{ matrix.python-version }}
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          set -e
          PY_TAG="cp$(echo \"$PYTHON_VERSION\" | tr -d .)"
          wheel=$(find /wheels -name "*${PY_TAG}*musllinux_1_1_x86_64.whl" | head -n 1)

          echo "Found wheel: $wheel"
          pip install tox
          pip install "$wheel"
          tox
          pip uninstall -y $(basename "$wheel" | cut -d- -f1) || true

      - name: Test sdist on Python ${{ matrix.python-version }}
        env:
          TOXENV: py${{ matrix.python-version }}
        run: |
          SDIST=$(ls /work/*.tar.gz | head -n 1)
          pip install "$SDIST"
          tox
      
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [test-wheels, test-sdist, test-alpine, test-emulated]

    steps:
      - name: Download built sdist
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: dist/

      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-wheels-*
          path: dist/

      - name: List contents to verify
        run: ls -R dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
