name: Build, Test, and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build wheels and sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: python -m pip install build cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS: "auto"

      - name: Build sdist
        run: python -m build --sdist --outdir dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: |
            wheelhouse/
            dist/*.tar.gz

  test-wheels:
    name: Test wheels on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    
    env:
      TOXENV: py${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: wheelhouse/

      - name: Install tox and wheel
        run: |
          python -m pip install tox
          python -m pip install wheelhouse/*.whl

      - name: Run tox
        run: tox

  test-sdist:
    name: Test sdist on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    
    env:
      TOXENV: py${{ matrix.python-version }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: dist/

      - name: Install from sdist
        run: |
          python -m pip install tox
          python -m pip install dist/*.tar.gz

      - name: Run tox
        run: tox

  test-alpine:
    name: Test on Alpine (musllinux)
    needs: build
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/musllinux_1_1_x86_64

    steps:
      - name: Install Alpine dependencies
        run: |
          apk add --no-cache python3 py3-pip py3-wheel py3-setuptools py3-tox

      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: wheelhouse/

      - name: Install wheel + tox
        run: |
          pip install wheelhouse/*.whl
          pip install tox

      - name: Run tox
        run: tox

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [test-wheels, test-sdist, test-alpine]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
